/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedFreezerRouteImport } from './routes/_authenticated/freezer'
import { Route as AuthenticatedFridgeRouteImport } from './routes/_authenticated/fridge'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedKitchenRouteImport } from './routes/_authenticated/kitchen'
import { Route as AuthenticatedPetsRouteImport } from './routes/_authenticated/pets'
import { Route as AuthenticatedShoppingRouteImport } from './routes/_authenticated/shopping'
import { Route as AuthenticatedMealsPlannedMealIdRouteImport } from './routes/_authenticated/meals/$plannedMealId'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFreezerRoute = AuthenticatedFreezerRouteImport.update({
  id: '/freezer',
  path: '/freezer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFridgeRoute = AuthenticatedFridgeRouteImport.update({
  id: '/fridge',
  path: '/fridge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKitchenRoute = AuthenticatedKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPetsRoute = AuthenticatedPetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShoppingRoute = AuthenticatedShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMealsPlannedMealIdRoute =
  AuthenticatedMealsPlannedMealIdRouteImport.update({
    id: '/meals/$plannedMealId',
    path: '/meals/$plannedMealId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/freezer': typeof AuthenticatedFreezerRoute
  '/fridge': typeof AuthenticatedFridgeRoute
  '/home': typeof AuthenticatedHomeRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/pets': typeof AuthenticatedPetsRoute
  '/shopping': typeof AuthenticatedShoppingRoute
  '/meals/$plannedMealId': typeof AuthenticatedMealsPlannedMealIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/freezer': typeof AuthenticatedFreezerRoute
  '/fridge': typeof AuthenticatedFridgeRoute
  '/home': typeof AuthenticatedHomeRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/pets': typeof AuthenticatedPetsRoute
  '/shopping': typeof AuthenticatedShoppingRoute
  '/meals/$plannedMealId': typeof AuthenticatedMealsPlannedMealIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/freezer': typeof AuthenticatedFreezerRoute
  '/_authenticated/fridge': typeof AuthenticatedFridgeRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/kitchen': typeof AuthenticatedKitchenRoute
  '/_authenticated/pets': typeof AuthenticatedPetsRoute
  '/_authenticated/shopping': typeof AuthenticatedShoppingRoute
  '/_authenticated/meals/$plannedMealId': typeof AuthenticatedMealsPlannedMealIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/freezer'
    | '/fridge'
    | '/home'
    | '/kitchen'
    | '/pets'
    | '/shopping'
    | '/meals/$plannedMealId'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/freezer'
    | '/fridge'
    | '/home'
    | '/kitchen'
    | '/pets'
    | '/shopping'
    | '/meals/$plannedMealId'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/freezer'
    | '/_authenticated/fridge'
    | '/_authenticated/home'
    | '/_authenticated/kitchen'
    | '/_authenticated/pets'
    | '/_authenticated/shopping'
    | '/_authenticated/meals/$plannedMealId'
    | '/_authenticated/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/freezer': {
      id: '/_authenticated/freezer'
      path: '/freezer'
      fullPath: '/freezer'
      preLoaderRoute: typeof AuthenticatedFreezerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fridge': {
      id: '/_authenticated/fridge'
      path: '/fridge'
      fullPath: '/fridge'
      preLoaderRoute: typeof AuthenticatedFridgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kitchen': {
      id: '/_authenticated/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof AuthenticatedKitchenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pets': {
      id: '/_authenticated/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof AuthenticatedPetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shopping': {
      id: '/_authenticated/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AuthenticatedShoppingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meals/$plannedMealId': {
      id: '/_authenticated/meals/$plannedMealId'
      path: '/meals/$plannedMealId'
      fullPath: '/meals/$plannedMealId'
      preLoaderRoute: typeof AuthenticatedMealsPlannedMealIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFreezerRoute: typeof AuthenticatedFreezerRoute
  AuthenticatedFridgeRoute: typeof AuthenticatedFridgeRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedKitchenRoute: typeof AuthenticatedKitchenRoute
  AuthenticatedPetsRoute: typeof AuthenticatedPetsRoute
  AuthenticatedShoppingRoute: typeof AuthenticatedShoppingRoute
  AuthenticatedMealsPlannedMealIdRoute: typeof AuthenticatedMealsPlannedMealIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFreezerRoute: AuthenticatedFreezerRoute,
  AuthenticatedFridgeRoute: AuthenticatedFridgeRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedKitchenRoute: AuthenticatedKitchenRoute,
  AuthenticatedPetsRoute: AuthenticatedPetsRoute,
  AuthenticatedShoppingRoute: AuthenticatedShoppingRoute,
  AuthenticatedMealsPlannedMealIdRoute: AuthenticatedMealsPlannedMealIdRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
