// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byhkvtjsfazgcfztlwry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5aGt2dGpzZmF6Z2NmenRsd3J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcwMTI2NDAsImV4cCI6MjEwMjU4ODY0MH0.Xq9WwnqXJkefxwmfS0tqZKCMJq75DBx00kqDxvNS0_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});